#ifndef KEYGEN_H
#define KEYGEN_H

#include <stdio.h>

#include "stream.h"

#define BYTES_PER_PERMUTATION 200

/* Generate a keyfile to be used by the full Vigenere cipher
 * Param pphrase: pass phrase
 * Param period: period of the key
 */
void keygen(const char *pphrase, int period);

/* Return a random int generated from a steam cipher
 * @Param buffer: a buffer of random integers generated by the stream cipher
 * @Param start: the start index of the buffer
 */
unsigned int RandomInteger(const unsigned char *buffer, int start);

/* swap the characters at position i and j in the string s */
void swap(char *s, int i, int j);

#endif
